# Generated by Django 3.1 on 2020-09-24 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empolyee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('resume', models.FileField(blank=True, upload_to='license')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('fields', multiselectfield.db.fields.MultiSelectField(choices=[('dev', 'development'), ('des', 'design'), ('fam', 'farming'), ('ter', 'translating'), ('tra', 'transformation'), ('con', 'content management'), ('led', 'leading'), ('acc', 'accounting'), ('ins', 'insurance')], max_length=35)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stablish_date', models.DateField()),
                ('location', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True, verbose_name='Linked In ')),
                ('address', models.CharField(max_length=300)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phone_number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999'. Up to 30 digits allowed.", regex='^\\+?1?\\d{4,30}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
