# Generated by Django 3.1 on 2020-09-24 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200924_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empolyee',
            new_name='Employee',
        ),
    ]
