# Generated by Django 3.1 on 2020-09-24 14:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200924_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='field',
            field=models.CharField(choices=[('dev', 'development'), ('des', 'design'), ('fam', 'farming'), ('ter', 'translating'), ('tra', 'transformation'), ('con', 'content management'), ('led', 'leading'), ('acc', 'accounting'), ('ins', 'insurance')], default='dev', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dev', 'development'), ('des', 'design'), ('fam', 'farming'), ('ter', 'translating'), ('tra', 'transformation'), ('con', 'content management'), ('led', 'leading'), ('acc', 'accounting'), ('ins', 'insurance')], max_length=30),
        ),
    ]
