# Generated by Django 3.1 on 2020-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200924_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
