# Generated by Django 3.1 on 2020-09-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_advertisement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('s', 'Seen'), ('ns', 'Not Seen'), ('ac', 'Accepted'), ('re', 'Rejected')], default='ns', max_length=3)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advertisement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
