# Generated by Django 3.1 on 2020-09-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200925_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='salary',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='min_salary',
            field=models.FloatField(default=0),
        ),
    ]
