# Generated by Django 3.1 on 2020-09-25 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200925_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default=0, max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999'. Up to 30 digits allowed.", regex='^\\+?1?\\d{4,30}$')]),
            preserve_default=False,
        ),
    ]
